/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HinnastoRouteImport } from './routes/hinnasto'
import { Route as KotitalouksilleRouteImport } from './routes/kotitalouksille'
import { Route as LatausasematRouteImport } from './routes/latausasemat'
import { Route as ReferenssitRouteImport } from './routes/referenssit'
import { Route as SahkosaneerausRouteImport } from './routes/sahkosaneeraus'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as YhteystiedotRouteImport } from './routes/yhteystiedot'
import { Route as YrityksilleRouteImport } from './routes/yrityksille'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HinnastoRoute = HinnastoRouteImport.update({
  id: '/hinnasto',
  path: '/hinnasto',
  getParentRoute: () => rootRouteImport,
} as any)
const KotitalouksilleRoute = KotitalouksilleRouteImport.update({
  id: '/kotitalouksille',
  path: '/kotitalouksille',
  getParentRoute: () => rootRouteImport,
} as any)
const LatausasematRoute = LatausasematRouteImport.update({
  id: '/latausasemat',
  path: '/latausasemat',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenssitRoute = ReferenssitRouteImport.update({
  id: '/referenssit',
  path: '/referenssit',
  getParentRoute: () => rootRouteImport,
} as any)
const SahkosaneerausRoute = SahkosaneerausRouteImport.update({
  id: '/sahkosaneeraus',
  path: '/sahkosaneeraus',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const YhteystiedotRoute = YhteystiedotRouteImport.update({
  id: '/yhteystiedot',
  path: '/yhteystiedot',
  getParentRoute: () => rootRouteImport,
} as any)
const YrityksilleRoute = YrityksilleRouteImport.update({
  id: '/yrityksille',
  path: '/yrityksille',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hinnasto': typeof HinnastoRoute
  '/kotitalouksille': typeof KotitalouksilleRoute
  '/latausasemat': typeof LatausasematRoute
  '/referenssit': typeof ReferenssitRoute
  '/sahkosaneeraus': typeof SahkosaneerausRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yhteystiedot': typeof YhteystiedotRoute
  '/yrityksille': typeof YrityksilleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hinnasto': typeof HinnastoRoute
  '/kotitalouksille': typeof KotitalouksilleRoute
  '/latausasemat': typeof LatausasematRoute
  '/referenssit': typeof ReferenssitRoute
  '/sahkosaneeraus': typeof SahkosaneerausRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yhteystiedot': typeof YhteystiedotRoute
  '/yrityksille': typeof YrityksilleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hinnasto': typeof HinnastoRoute
  '/kotitalouksille': typeof KotitalouksilleRoute
  '/latausasemat': typeof LatausasematRoute
  '/referenssit': typeof ReferenssitRoute
  '/sahkosaneeraus': typeof SahkosaneerausRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yhteystiedot': typeof YhteystiedotRoute
  '/yrityksille': typeof YrityksilleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hinnasto'
    | '/kotitalouksille'
    | '/latausasemat'
    | '/referenssit'
    | '/sahkosaneeraus'
    | '/sitemap.xml'
    | '/yhteystiedot'
    | '/yrityksille'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hinnasto'
    | '/kotitalouksille'
    | '/latausasemat'
    | '/referenssit'
    | '/sahkosaneeraus'
    | '/sitemap.xml'
    | '/yhteystiedot'
    | '/yrityksille'
  id:
    | '__root__'
    | '/'
    | '/hinnasto'
    | '/kotitalouksille'
    | '/latausasemat'
    | '/referenssit'
    | '/sahkosaneeraus'
    | '/sitemap.xml'
    | '/yhteystiedot'
    | '/yrityksille'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HinnastoRoute: typeof HinnastoRoute
  KotitalouksilleRoute: typeof KotitalouksilleRoute
  LatausasematRoute: typeof LatausasematRoute
  ReferenssitRoute: typeof ReferenssitRoute
  SahkosaneerausRoute: typeof SahkosaneerausRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  YhteystiedotRoute: typeof YhteystiedotRoute
  YrityksilleRoute: typeof YrityksilleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hinnasto': {
      id: '/hinnasto'
      path: '/hinnasto'
      fullPath: '/hinnasto'
      preLoaderRoute: typeof HinnastoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotitalouksille': {
      id: '/kotitalouksille'
      path: '/kotitalouksille'
      fullPath: '/kotitalouksille'
      preLoaderRoute: typeof KotitalouksilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latausasemat': {
      id: '/latausasemat'
      path: '/latausasemat'
      fullPath: '/latausasemat'
      preLoaderRoute: typeof LatausasematRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenssit': {
      id: '/referenssit'
      path: '/referenssit'
      fullPath: '/referenssit'
      preLoaderRoute: typeof ReferenssitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sahkosaneeraus': {
      id: '/sahkosaneeraus'
      path: '/sahkosaneeraus'
      fullPath: '/sahkosaneeraus'
      preLoaderRoute: typeof SahkosaneerausRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yhteystiedot': {
      id: '/yhteystiedot'
      path: '/yhteystiedot'
      fullPath: '/yhteystiedot'
      preLoaderRoute: typeof YhteystiedotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yrityksille': {
      id: '/yrityksille'
      path: '/yrityksille'
      fullPath: '/yrityksille'
      preLoaderRoute: typeof YrityksilleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HinnastoRoute: HinnastoRoute,
  KotitalouksilleRoute: KotitalouksilleRoute,
  LatausasematRoute: LatausasematRoute,
  ReferenssitRoute: ReferenssitRoute,
  SahkosaneerausRoute: SahkosaneerausRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  YhteystiedotRoute: YhteystiedotRoute,
  YrityksilleRoute: YrityksilleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
