/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YrityksilleRouteImport } from './routes/yrityksille'
import { Route as YhteystiedotRouteImport } from './routes/yhteystiedot'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenssitRouteImport } from './routes/referenssit'
import { Route as KotitalouksilleRouteImport } from './routes/kotitalouksille'
import { Route as IndexRouteImport } from './routes/index'

const YrityksilleRoute = YrityksilleRouteImport.update({
  id: '/yrityksille',
  path: '/yrityksille',
  getParentRoute: () => rootRouteImport,
} as any)
const YhteystiedotRoute = YhteystiedotRouteImport.update({
  id: '/yhteystiedot',
  path: '/yhteystiedot',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenssitRoute = ReferenssitRouteImport.update({
  id: '/referenssit',
  path: '/referenssit',
  getParentRoute: () => rootRouteImport,
} as any)
const KotitalouksilleRoute = KotitalouksilleRouteImport.update({
  id: '/kotitalouksille',
  path: '/kotitalouksille',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kotitalouksille': typeof KotitalouksilleRoute
  '/referenssit': typeof ReferenssitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yhteystiedot': typeof YhteystiedotRoute
  '/yrityksille': typeof YrityksilleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kotitalouksille': typeof KotitalouksilleRoute
  '/referenssit': typeof ReferenssitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yhteystiedot': typeof YhteystiedotRoute
  '/yrityksille': typeof YrityksilleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kotitalouksille': typeof KotitalouksilleRoute
  '/referenssit': typeof ReferenssitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yhteystiedot': typeof YhteystiedotRoute
  '/yrityksille': typeof YrityksilleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kotitalouksille'
    | '/referenssit'
    | '/sitemap.xml'
    | '/yhteystiedot'
    | '/yrityksille'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kotitalouksille'
    | '/referenssit'
    | '/sitemap.xml'
    | '/yhteystiedot'
    | '/yrityksille'
  id:
    | '__root__'
    | '/'
    | '/kotitalouksille'
    | '/referenssit'
    | '/sitemap.xml'
    | '/yhteystiedot'
    | '/yrityksille'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KotitalouksilleRoute: typeof KotitalouksilleRoute
  ReferenssitRoute: typeof ReferenssitRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  YhteystiedotRoute: typeof YhteystiedotRoute
  YrityksilleRoute: typeof YrityksilleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yrityksille': {
      id: '/yrityksille'
      path: '/yrityksille'
      fullPath: '/yrityksille'
      preLoaderRoute: typeof YrityksilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yhteystiedot': {
      id: '/yhteystiedot'
      path: '/yhteystiedot'
      fullPath: '/yhteystiedot'
      preLoaderRoute: typeof YhteystiedotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenssit': {
      id: '/referenssit'
      path: '/referenssit'
      fullPath: '/referenssit'
      preLoaderRoute: typeof ReferenssitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotitalouksille': {
      id: '/kotitalouksille'
      path: '/kotitalouksille'
      fullPath: '/kotitalouksille'
      preLoaderRoute: typeof KotitalouksilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KotitalouksilleRoute: KotitalouksilleRoute,
  ReferenssitRoute: ReferenssitRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  YhteystiedotRoute: YhteystiedotRoute,
  YrityksilleRoute: YrityksilleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
